name: TestCI

on:
  workflow_dispatch:

jobs:
  python_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install allure-pytest pytest

      - name: Run tests
        run: pytest -v --alluredir=allure-results

      - name: Check work directory contents
        run: ls -la
    
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure_report
          path: reports/
