
name: TestAllureCI

on:
  workflow_dispatch:

jobs:
  python_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install allure-pytest pytest

      - name: Run tests
        run: pytest -v --alluredir=allure-results

      - name: Check work directory contents
        if: ${{ always() }}
        run: ls -la
    
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()  # Такая запись аналог той с ${{}}, это старый короткий синтаксис
        with:
          ref: gh-pages  # Указание, что клонируем ветку gh-pages
          path: gh-pages  # Клонируем в директорию gh-pages (создается в раб директории раннера)

      - name: Check work directory contents
        if: ${{ always() }}
        run: ls -la

      - uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results  # Директория с результатами тестов
          gh_pages: gh-pages  # Директория, куда склонировалась ветка gh-pages (получается с прошлым отчетом)
          allure_report: allure-report  # Директория, в которую Allure запишет сгенерированный отчет (чистый HTML-отчёт без истории)
          allure_history: allure-history  # Директория, которая будет опубликована на GitHub Pages (финальный отчёт с историей)

      - name: Check work directory contents
        if: ${{ always() }}
        run: ls -la

      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.CI_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with: 
            authToken: ${{secrets.CI_TOKEN}}
            context: 'Test report'
            state: 'success'
            sha: ${{ github.event.pull_request.head.sha }}
            target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
